spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.175.3/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 911911
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
    context-path: /sell
    port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  //path: E:\sell/var/log/tomcat/
#  file: E:\sell/var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug//指定这个类的日志级别是debug
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 1483469312
  AppId: wx6ad144e54af67d87
  AppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#  将数据库语句后台查看
logging:
    level:
      com.imooc.dataobject.mapper: trace
mybatis:
    mapper-locations: classpath:mapper/*.xml

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 0
  database: 0
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0



